### ISSUE TITLE
Test vectors?

### ISSUE THREAD

**Issue by ecorm** [Melown/half#1]
Not an issue, but a general question of relevance: Is there a test suite somewhere with a comprehensive list of half float values with their corresponding decimal values? The [Wikipedia article](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) has only a small handful of test vectors. I'm having trouble finding more samples, and I don't trust myself to calculate them by hand.

It doesn't have to be a test suite tailored to this library, but any one dealing with 16-bit IEEE floats. In particular, I'd like to see more corner cases involved with rounding to nearest.

**Comment by vaclavblazek** [comment]
Please, refer to upstream. This is a library we imported from https://sourceforge.net/projects/half/ and use in our projects.

**Comment by ecorm** [comment]
Yes I know it's from Christian Rau and is hosted on SourceForge. I was just hoping that someone here knew of an existing test suite - any half float test suite.

I'll try asking the original author, but the academic types publishing these sorts of libraries aren't always willing/able to provide support to the general community.

**Comment by vaclavblazek** [comment]
Unfortunately, I do not know about any tests. We are happy that there is a freely available implementation that does (or seems to do) what it promises. IIRC, we use it only for converting between floats and half floats in our data formats.

**Comment by ecorm** [comment]
I have found the following:

- https://devblogs.microsoft.com/dotnet/introducing-the-half-type/
- https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/System/HalfTests.cs
- http://www.jhauser.us/arithmetic/TestFloat.html

~~While they don't have handy test vectors I can borrow~~ (.NET 5 does), I can still use them to generate the 16-bit float representations of various corner cases. Alternatively, I could even generate test vectors for the entire set of all possible 16-bit float representations, seeing that there are "only" 65536 cases.

**Comment by ecorm** [comment]
The [GetHashCode](https://docs.microsoft.com/en-us/dotnet/api/system.half.gethashcode?view=net-5.0#System_Half_GetHashCode) method of .NET 5's new `Half` struct returns the 16-bit integer representation of the number's bits.

The `Half` API does not seem to expose a direct way of initializing a number from raw bytes, so I had to use [System.Runtime.InteropServices.Marshall](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal?view=net-5.0) (in lieu of unsafe pointer manipulations).

This works for me:

```c#
using System;
using System.Runtime.InteropServices;

namespace float16test
{
    class Program
    {
        static Half BytesToHalf(ushort bits)
        {
            byte [] bytes = new byte[2] {(byte)(bits & 0xff), (byte)(bits >> 8)};
            Half half = (Half)0;
            int size = Marshal.SizeOf(half);
            IntPtr i = Marshal.AllocHGlobal(size);
            Marshal.Copy(bytes, 0, i, size);
            half = (Half)Marshal.PtrToStructure(i, half.GetType());
            Marshal.FreeHGlobal(i);
            return half;
        }

        static void Main(string[] args)
        {
            Half half = (Half)0.33325195;
            Console.WriteLine("0x{0:X4}", half.GetHashCode()); // prints 0x3555

            Console.WriteLine(BytesToHalf(0x3555).ToString()); // prints 0.3333
        }
    }
}
```

I'll share my test vectors here when I come up with them. I hope this helps someone else in the same predicament as me.

**Comment by ecorm** [comment]
For those following this, I discovered that the .NET 5 `Half` has a defect when converting `Half` subnormals to `Single`/`Double`: https://github.com/dotnet/runtime/issues/46515

The .NET 5 unit test for `Half` can be found here, which contains a few additional test vectors not found on Wikipedia: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/System/HalfTests.cs

I'll later share my test vectors here and will close this issue.

**Comment by ecorm** [comment]
As promised, here are my test vectors: https://gist.github.com/ecorm/3b5963749752f2cc2f96fb493d29fcba

16-bit float library authors and maintainers may use them as they see fit. Provided "as is" with no warranty.
